// Type declarations for CSS imports used by the Expo web template.
// expo-env.d.ts (generated by `expo start`) normally provides these; this file
// makes type-checking pass before the app has been started once.

declare module "*.css" {
  const content: { readonly [className: string]: string };
  export default content;
}

declare module "*.module.css" {
  const classes: { readonly [className: string]: string };
  export default classes;
}
